#!/usr/bin/env bash

set -euo pipefail

GAME_DIR="$HOME/Games/star-citizen"
CUDA_PATCH="$GAME_DIR/libcuda.patched.so"

# Novideo GPU?
echo "========== GPU Detection =========="
if ! lspci | grep -iq nvidia; then
  echo "✘ No NVIDIA graphics card found. Exiting."
  exit 1
fi
echo "✔ NVIDIA GPU detected."

# Ensure required scripts are executable
chmod +x "$GAME_DIR/mount_libcuda.sh" "$GAME_DIR/launchoptions.sh" "$GAME_DIR/patchcuda.sh"

# Check if libcuda.so is patched or changed else skip
"$GAME_DIR/patchcuda.sh"

# Mount patched libcuda since LD_PRELOAD and LD_LIBRARY_PATH is now blocked by EAC as injection method
"$GAME_DIR/mount_libcuda.sh"

# Launch the game scripts
"$GAME_DIR/launchoptions.sh"
